name: Prepare a conda environment for NNPDF installation

# This composite action prepares a conda environment with a set of shared settings
# that all NNPDF workflows should utilize.
# see https://docs.github.com/en/actions/sharing-automations/creating-actions/creating-a-composite-action

# Use it as a step of your workflow as:
# - uses: ./.github/actions/install_conda_pip
#
# It is possible to modify the python version of the default environment with
#         with:
#           python-version: "3.12"
#
# Remember that these actions are only available after checking out the repository,
# which should always be the first step!
# - uses: actions/checkout@v4

inputs:
  python-version:
    required: true
    description: "Python version to use"
    default: "3.12"

runs:
  using: "composite"
  steps:
    - uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: ${{ inputs.python-version }}
        use-mamba: true
        channels: https://packages.nnpdf.science/public,conda-forge
        show-channel-urls: true
        auto-update-conda: true
        activate-environment: nnpdf_environment
        conda-remove-defaults: true
    - name: Add NETRC
      shell: bash -l {0}
      run: |
        echo "$NETRC_FILE" | base64 --decode > ~/.netrc
