#
# Configuration file for NNPDF++
#
description: "NNPDF4.0 NLO global, deuteron and nuclear uncertainties. Runcard for the alpha_s variation NLO fit, pending iteration. alphas=0.117"

############################################################
# frac: training fraction
# ewk: apply ewk k-factors
# sys: systematics treatment (see systypes)
#

NLODatasets: &NLODatasets
- {dataset: NMCPD_dw_ite, frac: 0.75}
- {dataset: NMC, frac: 0.75}
- {dataset: SLACP_dwsh, frac: 0.75}
- {dataset: SLACD_dw_ite, frac: 0.75}
- {dataset: BCDMSP_dwsh, frac: 0.75}
- {dataset: BCDMSD_dw_ite, frac: 0.75}
- {dataset: CHORUSNUPb_dw_ite, frac: 0.75}
- {dataset: CHORUSNBPb_dw_ite, frac: 0.75}
- {dataset: NTVNUDMNFe_dw_ite, frac: 0.75, cfac: []}
- {dataset: NTVNBDMNFe_dw_ite, frac: 0.75, cfac: []}
- {dataset: HERACOMBNCEM, frac: 0.75}
- {dataset: HERACOMBNCEP460, frac: 0.75}
- {dataset: HERACOMBNCEP575, frac: 0.75}
- {dataset: HERACOMBNCEP820, frac: 0.75}
- {dataset: HERACOMBNCEP920, frac: 0.75}
- {dataset: HERACOMBCCEM, frac: 0.75}
- {dataset: HERACOMBCCEP, frac: 0.75}
- {dataset: HERACOMB_SIGMARED_C, frac: 0.75}   
- {dataset: HERACOMB_SIGMARED_B, frac: 0.75}   
- {dataset: DYE886R_dw_ite, frac: 1.0}
- {dataset: DYE886P, frac: 0.75, cfac: []}
- {dataset: DYE605_dw_ite, frac: 0.75, cfac: []}
- {dataset: CDFZRAP_NEW, frac: 1.0, cfac: []}
- {dataset: D0ZRAP, frac: 1.0, cfac: []}
- {dataset: D0WMASY, frac: 1.0, cfac: []}
- {dataset: ATLASWZRAP36PB, frac: 1.0, cfac: []}
- {dataset: ATLASZHIGHMASS49FB, frac: 1.0, cfac: []}
- {dataset: ATLASLOMASSDY11EXT, frac: 1.0, cfac: []}
- {dataset: ATLASWZRAP11CC, frac: 0.75, cfac: []}               
- {dataset: ATLASWZRAP11CF, frac: 0.75, cfac: []}               
- {dataset: ATLASDY2D8TEV, frac: 0.75, cfac: []}             
- {dataset: ATLAS_WZ_TOT_13TEV, frac: 1.0, cfac: [NRM]}       
- {dataset: ATLAS_WP_JET_8TEV_PT, frac: 0.75, cfac: []}         
- {dataset: ATLAS_WM_JET_8TEV_PT, frac: 0.75, cfac: []}
- {dataset: ATLAS_WCHARM_WP_DIFF_7TEV, frac: 1.0, cfac: []}
- {dataset: ATLAS_WCHARM_WM_DIFF_7TEV, frac: 1.0, cfac: []}
- {dataset: ATLASZPT8TEVMDIST, frac: 0.75, cfac: []}
- {dataset: ATLASZPT8TEVYDIST, frac: 0.75, cfac: []}
- {dataset: ATLASTTBARTOT, frac: 1.0, cfac: []}
- {dataset: ATLAS_TTB_DIFF_8TEV_LJ_TRAPNORM, frac: 1.0, cfac: []}                 
- {dataset: ATLAS_TTB_DIFF_8TEV_LJ_TTRAPNORM, frac: 1.0, cfac: []}                
- {dataset: ATLAS_TOPDIFF_DILEPT_8TEV_TTRAPNORM, frac: 1.0, cfac: []}             
- {dataset: ATLAS_1JET_8TEV_R06_DEC, frac: 0.75, cfac: []}                        
- {dataset: ATLAS_2JET_7TEV_R06, frac: 0.75, cfac: []}                            
- {dataset: ATLASPHT15, frac: 0.75, cfac: [EWK]}                                
- {dataset: ATLAS_SINGLETOP_TCH_R_7TEV, frac: 1.0, cfac: []}                      
- {dataset: ATLAS_SINGLETOP_TCH_R_13TEV, frac: 1.0, cfac: []}                     
- {dataset: ATLAS_SINGLETOP_TCH_DIFF_7TEV_T_RAP_NORM, frac: 1.0, cfac: []}        
- {dataset: ATLAS_SINGLETOP_TCH_DIFF_7TEV_TBAR_RAP_NORM, frac: 1.0, cfac: []}     
- {dataset: ATLAS_SINGLETOP_TCH_DIFF_8TEV_T_RAP_NORM, frac: 0.75, cfac: []}       
- {dataset: ATLAS_SINGLETOP_TCH_DIFF_8TEV_TBAR_RAP_NORM, frac: 0.75, cfac: []}    
- {dataset: CMSWEASY840PB, frac: 1.0, cfac: []}
- {dataset: CMSWMASY47FB, frac: 1.0, cfac: []}
- {dataset: CMSDY2D11, frac: 0.75, cfac: []}
- {dataset: CMSWMU8TEV, frac: 1.0, cfac: []}
- {dataset: CMSZDIFF12, frac: 1.0, cfac: [NRM]}
- {dataset: CMS_2JET_7TEV, frac: 0.75, cfac: []}                                   
- {dataset: CMS_2JET_3D_8TEV, frac: 0.75, cfac: []}                               
- {dataset: CMSTTBARTOT, frac: 1.0, cfac: []}
- {dataset: CMSTOPDIFF8TEVTTRAPNORM, frac: 1.0, cfac: []}
- {dataset: CMSTTBARTOT5TEV, frac: 1.0, cfac: []}                                 
- {dataset: CMS_TTBAR_2D_DIFF_MTT_TRAP_NORM, frac: 1.0, cfac: []}                 
- {dataset: CMS_TTB_DIFF_13TEV_2016_2L_TRAP, frac: 1.0, cfac: []}                 
- {dataset: CMS_TTB_DIFF_13TEV_2016_LJ_TRAP, frac: 1.0, cfac: []}                 
- {dataset: CMS_SINGLETOP_TCH_TOT_7TEV, frac: 1.0, cfac: []}                      
- {dataset: CMS_SINGLETOP_TCH_R_8TEV, frac: 1.0, cfac: []}                        
- {dataset: CMS_SINGLETOP_TCH_R_13TEV, frac: 1.0, cfac: []}
- {dataset: CMSWCHARMTOT, frac: 1.0}
- {dataset: CMSWCHARMRAT, frac: 1.0}
- {dataset: CMS_WCHARM_DIFF_UNNORM_13TEV}
- {dataset: LHCBZ940PB, frac: 1.0, cfac: []}
- {dataset: LHCBZEE2FB, frac: 1.0, cfac: []}
- {dataset: LHCBWZMU7TEV, frac: 1.0, cfac: [NRM]}
- {dataset: LHCBWZMU8TEV, frac: 1.0, cfac: [NRM]}
- {dataset: LHCB_Z_13TEV_DIMUON, frac: 1.0, cfac: []}                             
- {dataset: LHCB_Z_13TEV_DIELECTRON, frac: 1.0, cfac: []}                         


dataset_inputs: *NLODatasets

# These are needed for the similarity cuts
NNLODatasets: &NNLODatasets
- {dataset: NMCPD_dw_ite, frac: 0.75}
- {dataset: NMC, frac: 0.75}
- {dataset: SLACP_dwsh, frac: 0.75}
- {dataset: SLACD_dw_ite, frac: 0.75}
- {dataset: BCDMSP_dwsh, frac: 0.75}
- {dataset: BCDMSD_dw_ite, frac: 0.75}
- {dataset: CHORUSNUPb_dw_ite, frac: 0.75}
- {dataset: CHORUSNBPb_dw_ite, frac: 0.75}
- {dataset: NTVNUDMNFe_dw_ite, frac: 0.75, cfac: [MAS]}
- {dataset: NTVNBDMNFe_dw_ite, frac: 0.75, cfac: [MAS]}
- {dataset: HERACOMBNCEM, frac: 0.75}
- {dataset: HERACOMBNCEP460, frac: 0.75}
- {dataset: HERACOMBNCEP575, frac: 0.75}
- {dataset: HERACOMBNCEP820, frac: 0.75}
- {dataset: HERACOMBNCEP920, frac: 0.75}
- {dataset: HERACOMBCCEM, frac: 0.75}
- {dataset: HERACOMBCCEP, frac: 0.75}
- {dataset: HERACOMB_SIGMARED_C, frac: 0.75}   
- {dataset: HERACOMB_SIGMARED_B, frac: 0.75}   
- {dataset: DYE886R_dw_ite, frac: 1.0}
- {dataset: DYE886P, frac: 0.75, cfac: [QCD]}
- {dataset: DYE605_dw_ite, frac: 0.75, cfac: [QCD]}
- {dataset: CDFZRAP_NEW, frac: 1.0, cfac: [QCD]}
- {dataset: D0ZRAP, frac: 1.0, cfac: [QCD]}
- {dataset: D0WMASY, frac: 1.0, cfac: [QCD]}
- {dataset: ATLASWZRAP36PB, frac: 1.0, cfac: [QCD]}
- {dataset: ATLASZHIGHMASS49FB, frac: 1.0, cfac: [QCD]}
- {dataset: ATLASLOMASSDY11EXT, frac: 1.0, cfac: [QCD]}
- {dataset: ATLASWZRAP11CC, frac: 0.75, cfac: [QCD]}               
- {dataset: ATLASWZRAP11CF, frac: 0.75, cfac: [QCD]}               
- {dataset: ATLASDY2D8TEV, frac: 0.75, cfac: [QCDEWK]}             
- {dataset: ATLAS_WZ_TOT_13TEV, frac: 1.0, cfac: [NRM, QCD]}
# - {dataset: ATLAS_WCHARM_WP_DIFF_7TEV, frac: 1.0} # No Cfactors at NNLO
# - {dataset: ATLAS_WCHARM_WM_DIFF_7TEV, frac: 1.0} # No Cfactors at NNLO
- {dataset: ATLAS_WP_JET_8TEV_PT, frac: 0.75, cfac: [QCD]}         
- {dataset: ATLAS_WM_JET_8TEV_PT, frac: 0.75, cfac: [QCD]}         
- {dataset: ATLASZPT8TEVMDIST, frac: 0.75, cfac: [QCD], sys: 10}
- {dataset: ATLASZPT8TEVYDIST, frac: 0.75, cfac: [QCD], sys: 10}
- {dataset: ATLASTTBARTOT, frac: 1.0, cfac: [QCD]}
- {dataset: ATLAS_TTB_DIFF_8TEV_LJ_TRAPNORM, frac: 1.0, cfac: [QCD]}                 
- {dataset: ATLAS_TTB_DIFF_8TEV_LJ_TTRAPNORM, frac: 1.0, cfac: [QCD]}                
- {dataset: ATLAS_TOPDIFF_DILEPT_8TEV_TTRAPNORM, frac: 1.0, cfac: [QCD]}             
- {dataset: ATLAS_1JET_8TEV_R06_DEC, frac: 0.75, cfac: [QCD]}                        
- {dataset: ATLAS_2JET_7TEV_R06, frac: 0.75, cfac: [QCD]}                            
- {dataset: ATLASPHT15, frac: 0.75, cfac: [QCD, EWK]}                                
- {dataset: ATLAS_SINGLETOP_TCH_R_7TEV, frac: 1.0, cfac: [QCD]}                      
- {dataset: ATLAS_SINGLETOP_TCH_R_13TEV, frac: 1.0, cfac: [QCD]}                     
- {dataset: ATLAS_SINGLETOP_TCH_DIFF_7TEV_T_RAP_NORM, frac: 1.0, cfac: [QCD]}        
- {dataset: ATLAS_SINGLETOP_TCH_DIFF_7TEV_TBAR_RAP_NORM, frac: 1.0, cfac: [QCD]}     
- {dataset: ATLAS_SINGLETOP_TCH_DIFF_8TEV_T_RAP_NORM, frac: 0.75, cfac: [QCD]}       
- {dataset: ATLAS_SINGLETOP_TCH_DIFF_8TEV_TBAR_RAP_NORM, frac: 0.75, cfac: [QCD]}    
- {dataset: CMSWEASY840PB, frac: 1.0, cfac: [QCD]}
- {dataset: CMSWMASY47FB, frac: 1.0, cfac: [QCD]}
- {dataset: CMSDY2D11, frac: 0.75, cfac: [QCD]}
- {dataset: CMSWMU8TEV, frac: 1.0, cfac: [QCD]}
- {dataset: CMSZDIFF12, frac: 1.0, cfac: [QCD, NRM], sys: 10}
- {dataset: CMS_2JET_7TEV, frac: 0.75, cfac: [QCD]}                                   
- {dataset: CMS_2JET_3D_8TEV, frac: 0.75, cfac: [QCD]}                               
- {dataset: CMSTTBARTOT, frac: 1.0, cfac: [QCD]}
- {dataset: CMSTOPDIFF8TEVTTRAPNORM, frac: 1.0, cfac: [QCD]}
- {dataset: CMSTTBARTOT5TEV, frac: 1.0, cfac: [QCD]}                                 
- {dataset: CMS_TTBAR_2D_DIFF_MTT_TRAP_NORM, frac: 1.0, cfac: [QCD]}                 
- {dataset: CMS_TTB_DIFF_13TEV_2016_2L_TRAP, frac: 1.0, cfac: [QCD]}                 
- {dataset: CMS_TTB_DIFF_13TEV_2016_LJ_TRAP, frac: 1.0, cfac: [QCD]}                 
- {dataset: CMS_SINGLETOP_TCH_TOT_7TEV, frac: 1.0, cfac: [QCD]}                      
- {dataset: CMS_SINGLETOP_TCH_R_8TEV, frac: 1.0, cfac: [QCD]}                        
- {dataset: CMS_SINGLETOP_TCH_R_13TEV, frac: 1.0, cfac: [QCD]}
# - {dataset: CMSWCHARMTOT, frac: 1.0} # No Cfactors at NNLO
# - {dataset: CMSWCHARMRAT, frac: 1.0} # No Cfactors at NNLO
# - {dataset: CMS_WCHARM_DIFF_UNNORM_13TEV} # No Cfactors at NNLO
- {dataset: LHCBZ940PB, frac: 1.0, cfac: [QCD]}
- {dataset: LHCBZEE2FB, frac: 1.0, cfac: [QCD]}
- {dataset: LHCBWZMU7TEV, frac: 1.0, cfac: [NRM, QCD]}
- {dataset: LHCBWZMU8TEV, frac: 1.0, cfac: [NRM, QCD]}
- {dataset: LHCB_Z_13TEV_DIMUON, frac: 1.0, cfac: [QCD]}                             
- {dataset: LHCB_Z_13TEV_DIELECTRON, frac: 1.0, cfac: [QCD]}                         


do_not_require_similarity_for:
    - ATLAS_WCHARM_WP_DIFF_7TEV
    - ATLAS_WCHARM_WM_DIFF_7TEV
    - CMSWCHARMTOT
    - CMSWCHARMRAT
    - CMS_WCHARM_DIFF_UNNORM_13TEV


cut_similarity_threshold: 2

cuts_intersection_spec:
    # Note: This is using the alpha_s=0.118 theory on purpose, to keep cuts
    # constant across alpha_s variations
    - theoryid: 208
      pdf: NNPDF31_nlo_as_0118
      dataset_inputs: *NLODatasets

    - theoryid: 200
      pdf: NNPDF31_nlo_as_0118
      dataset_inputs: *NNLODatasets



############################################################
datacuts:
  t0pdfset: NNPDF31_nlo_as_0118 # PDF set to generate t0 covmat
  q2min: 3.49                        # Q2 minimum
  w2min: 12.5                        # W2 minimum
  use_cuts: fromsimilarpredictions

############################################################
theory:
  theoryid: 209     # database id

############################################################
fitting:
  trvlseed: 475038818
  nnseed: 2394641471
  mcseed: 1831662593
  save: false
  genrep: true      # true = generate MC replicas, false = use real data

  parameters: # This defines the parameter dictionary that is passed to the Model Trainer
    nodes_per_layer: [25, 20, 8]
    activation_per_layer: [tanh, tanh, linear]
    initializer: glorot_normal
    optimizer:
      clipnorm: 6.073e-6
      learning_rate: 2.621e-3
      optimizer_name: Nadam
    epochs: 17000
    positivity:
      initial: 184.8
      multiplier:
    integrability:
      initial: 10
      multiplier:
    stopping_patience: 0.1
    layer_type: dense
    dropout: 0.0
    threshold_chi2: 3.5

  # EVOL(QED) = sng=0,g=1,v=2,v3=3,v8=4,t3=5,t8=6,(pht=7)
  # EVOLS(QED)= sng=0,g=1,v=2,v8=4,t3=4,t8=5,ds=6,(pht=7)
  # FLVR(QED) = g=0, u=1, ubar=2, d=3, dbar=4, s=5, sbar=6, (pht=7)
  fitbasis: EVOL  # EVOL (7), EVOLQED (8), etc.
  basis:
  - {fl: sng, pos: false, trainable: false, mutsize: [15], mutprob: [0.05], smallx: [
      1.093, 1.121], largex: [1.486, 3.287]}
  - {fl: g, pos: false, trainable: false, mutsize: [15], mutprob: [0.05], smallx: [
      0.8329, 1.071], largex: [3.084, 6.767]}
  - {fl: v, pos: false, trainable: false, mutsize: [15], mutprob: [0.05], smallx: [
      0.5202, 0.7431], largex: [1.556, 3.639]}
  - {fl: v3, pos: false, trainable: false, mutsize: [15], mutprob: [0.05], smallx: [
      0.1205, 0.4839], largex: [1.736, 3.622]}
  - {fl: v8, pos: false, trainable: false, mutsize: [15], mutprob: [0.05], smallx: [
      0.5864, 0.7987], largex: [1.559, 3.569]}
  - {fl: t3, pos: false, trainable: false, mutsize: [15], mutprob: [0.05], smallx: [
      -0.5019, 1.126], largex: [1.754, 3.479]}
  - {fl: t8, pos: false, trainable: false, mutsize: [15], mutprob: [0.05], smallx: [
      0.6305, 0.8806], largex: [1.544, 3.481]}
  - {fl: t15, pos: false, trainable: false, mutsize: [15], mutprob: [0.05], smallx: [
      1.087, 1.139], largex: [1.48, 3.365]}

############################################################
positivity:
  posdatasets:
  - {dataset: POSF2U, poslambda: 1e6}        # Positivity Lagrange Multiplier
  - {dataset: POSF2DW, poslambda: 1e6}
  - {dataset: POSF2S, poslambda: 1e6}
  - {dataset: POSFLL, poslambda: 1e6}
  - {dataset: POSDYU, poslambda: 1e10}
  - {dataset: POSDYD, poslambda: 1e10}
  - {dataset: POSDYS, poslambda: 1e10}
  - {dataset: POSF2C, poslambda: 1e6}
  - {dataset: POSXUQ, poslambda: 1e6}        # Positivity of MSbar PDFs
  - {dataset: POSXUB, poslambda: 1e6}
  - {dataset: POSXDQ, poslambda: 1e6}
  - {dataset: POSXDB, poslambda: 1e6}
  - {dataset: POSXSQ, poslambda: 1e6}
  - {dataset: POSXSB, poslambda: 1e6}
  - {dataset: POSXGL, poslambda: 1e6}

############################################################
integrability:
  integdatasets:
  - {dataset: INTEGXT8, poslambda: 1e2}
  - {dataset: INTEGXT3, poslambda: 1e2}

############################################################
debug: false
maxcores: 4
