#
# Configuration file for n3fit
#
############################################################
description:  NNPDF4.0 candidate - NNLO - fitted charm
############################################################
# frac: training fraction
# ewk: apply ewk k-factors
# sys: systematics treatment (see systypes)
experiments:
# Fixed target DIS
- experiment: NMC
  datasets:
  - {dataset: NMCPD, frac: 0.5}
  - {dataset: NMC, frac: 0.5}
- experiment: SLAC
  datasets:
  - {dataset: SLACP, frac: 0.5}
  - {dataset: SLACD, frac: 0.5}
- experiment: BCDMS
  datasets:
  - {dataset: BCDMSP, frac: 0.5}
  - {dataset: BCDMSD, frac: 0.5}
- experiment: CHORUS
  datasets:
  - {dataset: CHORUSNUPb, frac: 0.5}
  - {dataset: CHORUSNBPb, frac: 0.5}
- experiment: NTVDMN
  datasets:
  - {dataset: NTVNUDMNFe, frac: 0.5}
  - {dataset: NTVNBDMNFe, frac: 0.5}
# HERA data
- experiment: HERACOMB
  datasets:
  - {dataset: HERACOMBNCEM, frac: 0.5}
  - {dataset: HERACOMBNCEP460, frac: 0.5}
  - {dataset: HERACOMBNCEP575, frac: 0.5}
  - {dataset: HERACOMBNCEP820, frac: 0.5}
  - {dataset: HERACOMBNCEP920, frac: 0.5}
  - {dataset: HERACOMBCCEM, frac: 0.5}
  - {dataset: HERACOMBCCEP, frac: 0.5}
# Combined HERA charm production cross-sections
- experiment: HERAF2CHARM
  datasets:
  - {dataset: HERACOMB_SIGMARED_C, frac: 0.5}
# Combined HERA bottom production cross-sections
- experiment: HERAF2BOTTOM
  datasets:
  - {dataset: HERACOMB_SIGMARED_B, frac: 0.5}
# Fixed target Drell-Yan
- experiment: DYE886
  datasets:
  - {dataset: DYE886R, frac: 1.0}
  - {dataset: DYE886P, frac: 0.5, cfac: [QCD]}
- experiment: DYE605
  datasets:
  - {dataset: DYE605, frac: 0.5, cfac: [QCD]}
# Tevatron jets and W,Z production
- experiment: CDF
  datasets:
  - {dataset: CDFZRAP, frac: 1.0, cfac: [QCD]}
- experiment: D0
  datasets:
  - {dataset: D0ZRAP, frac: 1.0, cfac: [QCD]}
  - {dataset: D0WEASY, frac: 1.0, cfac: [QCD]}
  - {dataset: D0WMASY, frac: 1.0, cfac: [QCD]}
# ATLAS
- experiment: ATLAS
  datasets:
  #EWK
  - {dataset: ATLASWZRAP36PB, frac: 1.0, cfac: [QCD]}
  - {dataset: ATLASZHIGHMASS49FB, frac: 1.0, cfac: [QCD]}
  - {dataset: ATLASLOMASSDY11EXT, frac: 1.0, cfac: [QCD]}
  - {dataset: ATLASWZRAP11, frac: 0.5, cfac: [QCD]}
  - {dataset: ATLASWZRAP11CC, frac: 0.5, cfac: [QCD]}
  - {dataset: ATLASWZRAP11CF, frac: 0.5, cfac: [QCD]}
  - {dataset: ATLAS_WZ_TOT_13TEV, frac: 1.0, cfac: [NRM,EWK,QCD]}
  - {dataset: ATLAS_WP_JET_8TEV_PT, frac: 0.5, cfac: [QCD]}
  - {dataset: ATLAS_WM_JET_8TEV_PT, frac: 0.5, cfac: [QCD]}
#  - {dataset: ATLAS_WP_JET_8TEV_PTJ, frac: 0.5, cfac: [QCD]}
#  - {dataset: ATLAS_WM_JET_8TEV_PTJ, frac: 0.5, cfac: [QCD]}
  #Z pT
  - {dataset: ATLASZPT8TEVMDIST, frac: 0.5, cfac: [QCD], sys: 10}
  - {dataset: ATLASZPT8TEVYDIST, frac: 0.5, cfac: [QCD], sys: 10}
  #SINGLE JETS
#  - {dataset: ATLAS1JET11_NEW_SCALE, frac: 0.5, cfac: [QCD,EWK]}
  - {dataset: ATLAS_1JET_8TEV_R06, frac: 0.5, cfac: [QCD,EWK]}
  #DIJETS
  - {dataset: ATLAS_2JET_7TEV_R06, frac: 0.5, cfac: [QCD, EWK]}
  #DIRECT PHOTON
  - {dataset: ATLASPHT12, frac: 0.5, cfac: [NRM,QCD,EWK]}
  - {dataset: ATLASPHT15, frac: 0.5, cfac: [QCD,EWK]}
  #TOP PAIR
  - {dataset: ATLASTTBARTOT, frac: 1.0, cfac: [QCD]}
  - {dataset: ATLAS_TTB_DIFF_8TEV_LJ_TPTNORM, frac: 1.0, cfac: [QCD]}
  - {dataset: ATLAS_TTB_DIFF_8TEV_LJ_TRAPNORM, frac: 1.0, cfac: [QCD]}
  - {dataset: ATLAS_TTB_DIFF_8TEV_LJ_TTRAPNORM, frac: 1.0, cfac: [QCD]}
  - {dataset: ATLAS_TTB_DIFF_8TEV_LJ_TTMNORM, frac: 1.0, cfac: [QCD]}
  - {dataset: ATLAS_TOPDIFF_DILEPT_8TEV_TTRAPNORM, frac: 1.0, cfac: [QCD]}
#  - {dataset: ATLAS_TOPDIFF_DILEPT_8TEV_TTMNORM, frac: 1.0, cfac: [QCD]}
  #SINGLE TOP
  - {dataset: ATLAS_SINGLETOP_TCH_R_7TEV, frac: 1.0, cfac: [QCD]}
  - {dataset: ATLAS_SINGLETOP_TCH_R_13TEV, frac: 1.0, cfac: [QCD]}
  - {dataset: ATLAS_SINGLETOP_TCH_DIFF_7TEV_T_RAP_NORM, frac: 1.0, cfac: [QCD]}
  - {dataset: ATLAS_SINGLETOP_TCH_DIFF_7TEV_TBAR_RAP_NORM, frac: 1.0, cfac: [QCD]}
#  - {dataset: ATLAS_SINGLETOP_TCH_DIFF_8TEV_T_PT, cfac: [QCD]}
#  - {dataset: ATLAS_SINGLETOP_TCH_DIFF_8TEV_TBAR_PT, cfac: [QCD]}
#  - {dataset: ATLAS_SINGLETOP_TCH_DIFF_8TEV_T_RAP, cfac: [QCD]}
#  - {dataset: ATLAS_SINGLETOP_TCH_DIFF_8TEV_TBAR_RAP, cfac: [QCD]}
#  - {dataset: ATLAS_SINGLETOP_TCH_DIFF_8TEV_T_PT_NORM, cfac: [QCD]}
#  - {dataset: ATLAS_SINGLETOP_TCH_DIFF_8TEV_TBAR_PT_NORM, cfac: [QCD]}
  - {dataset: ATLAS_SINGLETOP_TCH_DIFF_8TEV_T_RAP_NORM, cfac: [QCD]}
  - {dataset: ATLAS_SINGLETOP_TCH_DIFF_8TEV_TBAR_RAP_NORM, cfac: [QCD]}
# CMS
- experiment: CMS
  datasets:
  #EWK
  - {dataset: CMSWEASY840PB, frac: 1.0, cfac: [QCD]}
  - {dataset: CMSWMASY47FB, frac: 1.0, cfac: [QCD]}
  - {dataset: CMSDY2D11, frac: 0.5, cfac: [QCD]}
  - {dataset: CMSWMU8TEV, frac: 1.0, cfac: [QCD]}
  #Z pT
  - {dataset: CMSZDIFF12, frac: 1.0, cfac: [QCD, NRM], sys: 10}
  #SINGLE JETS
#  - {dataset: CMSJETS11_NEW_SCALE, frac: 0.5, cfac: [QCD,EWK]}
#  - {dataset: CMS_1JET_8TEV, frac: 0.5, cfac: [QCD,EWK]}
  #DIJETS
  - {dataset: CMS_2JET_7TEV, frac: 0.5, cfac: [QCD, EWK]}
  - {dataset: CMS_2JET_3D_8TEV, frac: 0.5, cfac: [QCD, EWK]}
  #TOP PAIR
  - {dataset: CMSTTBARTOT, frac: 1.0, cfac: [QCD]}
  - {dataset: CMSTTBARTOT5TEV, frac: 1.0, cfac: [QCD]}
  - {dataset: CMSTOPDIFF8TEVTTRAPNORM, frac: 1.0, cfac: [QCD]}
  - {dataset: CMS_TTBAR_2D_DIFF_MTT_TRAP_NORM, frac: 1.0, cfac: [QCD]}
#  - {dataset: CMS_TTBAR_2D_DIFF_MTT_TTRAP_NORM, frac: 1.0, cfac: [QCD]}
#  - {dataset: CMS_TTBAR_2D_DIFF_PT_TRAP_NORM, frac: 1.0, cfac: [QCD]}
#  - {dataset: CMS_TTB_DIFF_13TEV_2016_2L_TPT, frac: 1.0, cfac: [QCD]}
  - {dataset: CMS_TTB_DIFF_13TEV_2016_2L_TRAP, frac: 1.0, cfac: [QCD]}
#  - {dataset: CMS_TTB_DIFF_13TEV_2016_2L_TTM, frac: 1.0, cfac: [QCD]}
#  - {dataset: CMS_TTB_DIFF_13TEV_2016_2L_TTRAP, frac: 1.0, cfac: [QCD]}
#  - {dataset: CMS_TTB_DIFF_13TEV_2016_LJ_TPT, frac: 1.0, cfac: [QCD]}
  - {dataset: CMS_TTB_DIFF_13TEV_2016_LJ_TRAP, frac: 1.0, cfac: [QCD]}
#  - {dataset: CMS_TTB_DIFF_13TEV_2016_LJ_TTM, frac: 1.0, cfac: [QCD]}
#  - {dataset: CMS_TTB_DIFF_13TEV_2016_LJ_TTRAP, frac: 1.0, cfac: [QCD]}
  #SINGLE TOP
  - {dataset: CMS_SINGLETOP_TCH_TOT_7TEV, frac: 1.0, cfac: [QCD]}
  - {dataset: CMS_SINGLETOP_TCH_R_8TEV, frac: 1.0, cfac: [QCD]}
  - {dataset: CMS_SINGLETOP_TCH_R_13TEV, frac: 1.0, cfac: [QCD]}
# LHCb 
- experiment: LHCb
  datasets:
  - {dataset: LHCBZ940PB, frac: 1.0, cfac: [QCD]}
  - {dataset: LHCBZEE2FB, frac: 1.0, cfac: [QCD]}
  - {dataset: LHCBWZMU7TEV, frac: 1.0, cfac: [NRM, QCD]}
  - {dataset: LHCBWZMU8TEV, frac: 1.0, cfac: [NRM, QCD]}
  - {dataset: LHCB_Z_13TEV_DIMUON, frac: 1.0, cfac: [QCD]}
  - {dataset: LHCB_Z_13TEV_DIELECTRON, frac: 1.0, cfac: [QCD]}

############################################################
datacuts:
  t0pdfset: 200101-ern-dijets-nnlo                     # PDF set to generate t0 covmat
  q2min: 3.49                        # Q2 minimum
  w2min: 12.5                        # W2 minimum
  combocuts: NNPDF31                 # NNPDF3.0 final kin. cuts
  jetptcut_tev: 0                    # jet pt cut for tevatron
  jetptcut_lhc: 0                    # jet pt cut for lhc
  wptcut_lhc: 30.0                   # Minimum pT for W pT diff distributions
  jetycut_tev: 1e30                  # jet rap. cut for tevatron
  jetycut_lhc: 1e30                  # jet rap. cut for lhc
  dymasscut_min: 0                   # dy inv.mass. min cut
  dymasscut_max: 1e30                # dy inv.mass. max cut
  jetcfactcut: 1e30                  # jet cfact. cut

############################################################
theory:
  theoryid: 53        # database id

############################################################
fitting:
  trvlseed: 1
  nnseed: 2
  mcseed: 3
  seed: 9453862133528           # set the seed for the random generator
  genrep: on        # on = generate MC replicas, off = use real data
  rngalgo: 0        # 0 = ranlux, 1 = cmrg, see randomgenerator.cc
  fitmethod: NGA    # Minimization algorithm
  ngen: 30000       # Maximum number of generations
  nmutants: 80      # Number of mutants for replica
  paramtype: NN
  nnodes: [2, 5, 3, 1]

  parameters: # This defines the parameter dictionary that is passed to the Model Trainer
    nodes_per_layer: [55, 38, 28, 8]
    activation_per_layer: ['sigmoid', 'sigmoid', 'sigmoid', 'linear']
    initializer: 'glorot_normal'
    learning_rate: 1.0
    optimizer: 'Adadelta'
    epochs: 80000
    pos_multiplier: 1.05
    pos_initial: 1.1
    stopping_patience: 0.19 # percentage of the number of epochs
    layer_type: 'dense'
    dropout: 0.006



  # NN23(QED) = sng=0,g=1,v=2,t3=3,ds=4,sp=5,sm=6,(pht=7)
  # EVOL(QED) = sng=0,g=1,v=2,v3=3,v8=4,t3=5,t8=6,(pht=7)
  # EVOLS(QED)= sng=0,g=1,v=2,v8=4,t3=4,t8=5,ds=6,(pht=7)
  # FLVR(QED) = g=0, u=1, ubar=2, d=3, dbar=4, s=5, sbar=6, (pht=7)
  fitbasis: NN31IC # EVOL (7), EVOLQED (8), etc.
  basis:
      # remeber to change the name of PDF accordingly with fitbasis
      # pos: on for NN squared
      # mutsize: mutation size
      # mutprob: mutation probability
      # smallx, largex: preprocessing ranges
  - {fl: sng, pos: off, mutsize: [15], trainable: False, mutprob: [0.05], smallx: [1.062, 1.165], largex: [1.427, 2.763]}
  - {fl: g,   pos: off, mutsize: [15], trainable: False, mutprob: [0.05], smallx: [0.895, 1.279], largex: [0.0, 6.229]}
  - {fl: v,   pos: off, mutsize: [15], trainable: False, mutprob: [0.05], smallx: [0.5134, 0.7083], largex: [1.184, 2.598]}
  - {fl: v3,  pos: off, mutsize: [15], trainable: False, mutprob: [0.05], smallx: [0.2443, 0.5808], largex: [1.09, 2.99]}
  - {fl: v8,  pos: off, mutsize: [15], trainable: False, mutprob: [0.05], smallx: [0.5446, 0.7297], largex: [0.7528, 3.183]}
  - {fl: t3,  pos: off, mutsize: [15], trainable: False, mutprob: [0.05], smallx: [-0.5888, 1.508], largex: [1.754, 3.165]}
  - {fl: t8,  pos: off, mutsize: [15], trainable: False, mutprob: [0.05], smallx: [0.4786, 1.336], largex: [1.363, 2.917]}
  - {fl: cp,  pos: off, mutsize: [15], trainable: False, mutprob: [0.05], smallx: [-0.1992, 1.102], largex: [1.25, 7.916]}

############################################################
stopping:
  stopmethod: LOOKBACK  # Stopping method
  lbdelta: 0            # Delta for look-back stopping
  mingen: 0             # Minimum number of generations
  window: 500           # Window for moving average
  minchi2: 3.5          # Minimum chi2 
  minchi2exp: 6.0       # Minimum chi2 for experiments
  nsmear: 200           # Smear for stopping
  deltasm: 200          # Delta smear for stopping
  rv: 2                 # Ratio for validation stopping
  rt: 0.5               # Ratio for training stopping
  epsilon: 1e-6         # Gradient epsilon

############################################################
positivity:
  posdatasets:
  - {dataset: POSF2U, poslambda: 1e6}        # Positivity Lagrange Multiplier
  - {dataset: POSF2DW, poslambda: 1e6}
  - {dataset: POSF2S, poslambda: 1e6}
  - {dataset: POSFLL, poslambda: 1e6}
  - {dataset: POSDYU, poslambda: 1e10}
  - {dataset: POSDYD, poslambda: 1e10}
  - {dataset: POSDYS, poslambda: 1e10}

############################################################
closuretest:
  filterseed: 0     # Random seed to be used in filtering data partitions
  fakedata: off     # on = to use FAKEPDF to generate pseudo-data
  fakepdf: MSTW2008nlo68cl      # Theory input for pseudo-data
  errorsize: 1.0    # uncertainties rescaling
  fakenoise: off    # on = to add random fluctuations to pseudo-data
  rancutprob: 1.0   # Fraction of data to be included in the fit
  rancutmethod: 0   # Method to select rancutprob data fraction
  rancuttrnval: off # 0(1) to output training(valiation) chi2 in report
  printpdf4gen: off # To print info on PDFs during minimization

############################################################
lhagrid:
  nx: 150
  xmin: 1e-9
  xmed: 0.1
  xmax: 1.0
  nq: 50
  qmax: 1e5

############################################################
debug: off
