package:
    name: libnnpdf
    version: "{{ GIT_DESCRIBE_TAG[1:] }}.{{ GIT_DESCRIBE_NUMBER }}"

source:
    git_url: ../

requirements:
    build:
        - {{ compiler("cxx") }}
        - {{ compiler("c") }}
        - swig ==3.0.10
        - cmake
        #Found bug in 0.29.2 from the defaults channel
        #- pkg-config ==0.29.1
    host:
        - python
        - lhapdf
        - sqlite
        #Gsl doesn't link openblas on old debian 7
        - gsl ==2.2.1 0
        - numpy ==1.13
        - libarchive
        - yaml-cpp
    run:
        - lhapdf
        - python
        - sqlite
        - libgcc # [linux]
        - gsl ==2.2.1 0
        - numpy ==1.13
        - libarchive
        - yaml-cpp

build:
    number: 0
    detect_binary_files_with_prefix: True

test:
    commands:
        - nnpdf-config

about:
    home: https://nnpdf.hepforge.org/
    license: SECRET
