package:
    name: libnnpdf
    version: "{{ environ.get('GIT_DESCRIBE_TAG', '')[1:] }}.{{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}"

source:
    git_url: ../

requirements:
    build: 
        - python 
        - lhapdf
        - swig
        - sqlite
        - gcc <5
        - libgcc
        - gsl
        - numpy
        {% if environ.get("NNPDF_USE_DOUBLE", False) %}
        - nnpdf_use_double
        {% endif  %}
    run:
        - lhapdf
        - python 
        - sqlite
        - libgcc
        - gsl
        - numpy
        {% if environ.get("NNPDF_USE_DOUBLE", False) %}
        - nnpdf_use_double
        {% endif  %}

build:
    number: 0
    detect_binary_files_with_prefix: True
    {% if environ.get("NNPDF_USE_DOUBLE", False) %}
    features:
        - nnpdf_use_double
    {% endif  %}
    script_env:
        - NNPDF_USE_DOUBLE

test:
    commands:
        - nnpdf-config

about:
    home: https://nnpdf.hepforge.org/
    license: SECRET
