package:
    name: nnpdf
    version: "{{ GIT_DESCRIBE_TAG }}.{{ GIT_DESCRIBE_NUMBER }}+{{ GIT_DESCRIBE_HASH }}"

source:
    git_url: ../

requirements:
    build:
        - {{ compiler("cxx") }}
        - {{ compiler("c") }}
        - swig
        - cmake
        - pkg-config
    host:
        - lhapdf      # with python wrapper
        - sqlite
        - gsl         # Gsl doesn't link openblas on old debian 7
        - libarchive ==3.4.2 # See https://github.com/NNPDF/nnpdf/pull/1130
        - yaml-cpp
        - apfel >=3   # see https://github.com/scarrazza/apfel
        - python
        - numpy
    run:
        # Only install tensorflow on linux. Select eigen build
        - tensorflow >=2 *eigen* # [linux]
        - gast ==0.3.3 # Conda tensorflow uses the wrong version
        - opt_einsum >= 2.3.2 # Conda tensorflow uses the wrong version
        - psutil # to ensure n3fit affinity is with the right processors
        - hyperopt
        - seaborn
        - lhapdf
        - sqlite
        - gsl
        - numpy
        - libarchive
        - yaml-cpp
        - apfel
        - pkg-config
        - python # requirements for validphys
        - reportengine >=0.28.60 # see https://github.com/NNPDF/reportengine
        - matplotlib >=3.3.0
        - blessings >=1.7
        - scipy >=0.19.1
        - pandas
        - requests
        - prompt_toolkit
        - sphinx # documentation
        - recommonmark
        - sphinx_rtd_theme >0.5

test:
    requires:
        - hypothesis
        - pytest
        - coverage
        - pytest-mpl
        #Build dependencies for catch tests
        - {{ compiler("cxx") }}
        - {{ compiler("c") }}
        - swig ==3.0.10
        - cmake

    source_files:
        - "*"

build:
    number: 0
    detect_binary_files_with_prefix: True
    # import CONDA_BUILD_SYSROOT from env variable for osx
    script_env:
      - CONDA_BUILD_SYSROOT # [osx]

about:
    home: https://nnpdf.mi.infn.it/
    license: SECRET
    summary: "NNPDF analysis framework"
