package:
    name: nnpdf
    version: "{{ GIT_DESCRIBE_TAG }}.{{ GIT_DESCRIBE_NUMBER }}+{{ GIT_DESCRIBE_HASH }}"

source:
    git_url: ../

requirements:
    build:
        - {{ compiler("cxx") }}
        - {{ compiler("c") }}
        - swig ==3.0.10
        - cmake
        - pkg-config
    host:
        - lhapdf      # with python3.6 wrapper
        - sqlite
        - gsl         # Gsl doesn't link openblas on old debian 7
        - libarchive
        - yaml-cpp
        - apfel >=3   # see https://github.com/scarrazza/apfel
        - python
        - numpy
    run:
        - lhapdf
        - sqlite
        - gsl
        - numpy
        - libarchive
        - yaml-cpp
        - apfel
        - pkg-config
        - python # requirements for validphys
        - reportengine >=0.28 # see https://github.com/NNPDF/reportengine
        - matplotlib >=2.0.1,<3 | >=3.0.2
        - blessings
        - scipy >=0.19.1
        - pandas =0.23
        - requests
        - prompt_toolkit =2

test:
    requires:
        - hypothesis
        - pytest
        - coverage
        - pytest-mpl
        #Build dependencies for catch tests
        - {{ compiler("cxx") }}
        - {{ compiler("c") }}
        - swig ==3.0.10
        - cmake

    source_files:
        - "*"

build:
    number: 0
    detect_binary_files_with_prefix: True
    # import CONDA_BUILD_SYSROOT from env variable for osx
    script_env:
      - CONDA_BUILD_SYSROOT # [osx]

about:
    home: https://nnpdf.mi.infn.it/
    license: SECRET
    summary: "NNPDF analysis framework"
