package:
    name: nnpdf
    version: "{{ GIT_DESCRIBE_TAG }}.{{ GIT_DESCRIBE_NUMBER }}+{{ GIT_DESCRIBE_HASH }}"

source:
    git_url: ../

requirements:
    build:
        - {{ compiler("cxx") }}
        - {{ compiler("c") }}
        - swig
        - cmake
        - pkg-config
        # See https://github.com/NNPDF/nnpdf/pull/1280
        - sysroot_linux-64 >=2.17 # [linux]
    host:
        - lhapdf      # with python wrapper
        - apfel
        - numpy
        - yaml-cpp
        - libarchive
        - gsl         # Gsl doesn't link openblas on old debian 7
        - openssl >=3.0

test:
    requires:
        - hypothesis
        - pytest
        - coverage
        - pytest-mpl
        #Build dependencies for catch tests
        - {{ compiler("cxx") }}
        - {{ compiler("c") }}
        - sysroot_linux-64==2.17 # [linux]
        - swig ==3.0.10
        - cmake

    source_files:
        - "*"

build:
    number: 0
    detect_binary_files_with_prefix: True
    # import CONDA_BUILD_SYSROOT from env variable for osx
    script_env:
      - CONDA_BUILD_SYSROOT # [osx]

about:
    home: https://nnpdf.mi.infn.it/
    license: SECRET
    summary: "NNPDF analysis framework"
