package:
    name: nnpdf
    version: "{{ GIT_DESCRIBE_TAG }}.{{ GIT_DESCRIBE_NUMBER }}+{{ GIT_DESCRIBE_HASH }}"

source:
    git_url: ../

requirements:
    build:
        - {{ compiler("cxx") }}
        - {{ compiler("c") }}
        - swig
        - cmake
        - pkg-config
        # See https://github.com/NNPDF/nnpdf/pull/1280
        - sysroot_linux-64==2.17 # [linux]
    host:
        - lhapdf      # with python wrapper
        - sqlite
        - gsl         # Gsl doesn't link openblas on old debian 7
        - libarchive
        - yaml-cpp >=0.6.3
        - apfel >=3   # see https://github.com/scarrazza/apfel
        - python
        - numpy
        - poetry-core >=1.0.0
        - poetry-dynamic-versioning
    run:
        - tensorflow >=2.10
        - tensorflow >=2.10 *eigen* # [py < 311]
        - psutil # to ensure n3fit affinity is with the right processors
        - hyperopt
        - seaborn
        - lhapdf
        - sqlite
        - gsl
        - numpy
        - libarchive
        - yaml-cpp >=0.6.3
        - apfel
        - pkg-config
        - python # requirements for validphys
        - reportengine ==0.30.28  # see https://github.com/NNPDF/reportengine
        - matplotlib >=3.3.0,<3.8  # see https://github.com/NNPDF/nnpdf/pull/1809
        - blessings >=1.7
        - scipy >=0.19.1
        - pandas <2 # In principle the code runs with pandas 2 but the results (plots, tables, formats) are untested
        - requests
        - prompt_toolkit
        - validobj
        - sphinx >=4.0.2 # documentation. Needs pinning becasue https://github.com/sphinx-doc/sphinx/issues/9216
        - recommonmark
        - sphinx_rtd_theme >0.5
        - sphinxcontrib-bibtex
        - curio >=1.0
        - pineappl >=0.6.2
        - eko >=0.14.1
        - fiatlux

test:
    requires:
        - hypothesis
        - pytest
        - coverage
        - pytest-mpl
        #Build dependencies for catch tests
        - {{ compiler("cxx") }}
        - {{ compiler("c") }}
        - sysroot_linux-64==2.17 # [linux]
        - swig ==3.0.10
        - cmake

    source_files:
        - "*"

build:
    number: 0
    detect_binary_files_with_prefix: True
    # import CONDA_BUILD_SYSROOT from env variable for osx
    script_env:
      - CONDA_BUILD_SYSROOT # [osx]

about:
    home: https://nnpdf.mi.infn.it/
    license: SECRET
    summary: "NNPDF analysis framework"
