#
# Configuration file for n3fit
#
############################################################
description: Basic feature scaling

############################################################
dataset_inputs:
- {dataset: SLAC_NC_NOTFIXED_D_EM-F2, frac: 0.75, variant: legacy_dw}
- {dataset: NMC_NC_NOTFIXED_EM-F2, frac: 0.75, variant: legacy_dw}
- {dataset: CMS_1JET_8TEV_PTY, frac: 0.75, cfac: [], variant: legacy_data}

############################################################
datacuts:
  t0pdfset     : NNPDF40_nnlo_as_01180 # PDF set to generate t0 covmat
  q2min        : 3.49                # Q2 minimum
  w2min        : 12.5                # W2 minimum

############################################################
theory:
  theoryid: 41_000_000       # database id

############################################################
trvlseed: 1
nnseed: 2
mcseed: 3
genrep: True     # true = generate MC replicas, false = use real data
diagonal_basis: false

save: 'weights.h5'

tensorboard:
  weight_freq: 100
  profiling: False

parameters: # This defines the parameter dictionary that is passed to the Model Trainer
  nodes_per_layer: [15, 10, 8]
  activation_per_layer: ['sigmoid', 'sigmoid', 'linear']
  initializer: 'glorot_normal'
  optimizer:
    optimizer_name: 'RMSprop'
    learning_rate: 0.01
    clipnorm: 1.0
  epochs: 900
  positivity:
    multiplier: 1.05 # When any of the multiplier and/or the initial is not set
    initial: # the maxlambda will be used instead to compute these values per dataset
    threshold: 1e-5
  stopping_patience: 0.30 # percentage of the number of epochs
  layer_type: 'dense'
  dropout: 0.0
  feature_scaling_points: 40
  threshold_chi2: 5.0

fitting:
  fitbasis: NN31IC # EVOL (7), EVOLQED (8), etc.
  basis:
      # remeber to change the name of PDF accordingly with fitbasis
      - { fl: sng,  smallx: [1.05,1.19], trainable: False }
      - { fl: g,    smallx: [0.94,1.25], trainable: False }
      - { fl: v,    smallx: [0.54,0.75], trainable: False }
      - { fl: v3,   smallx: [0.21,0.57] }
      - { fl: v8,   smallx: [0.52,0.76], trainable: True }
      - { fl: t3,  smallx: [-0.37,1.52] }
      - { fl: t8,   smallx: [0.56,1.29] }
      - { fl: cp,   smallx: [0.12,1.19] }

############################################################
positivity:
  posdatasets:
  - {dataset: NNPDF_POS_2P24GEV_F2U, maxlambda: 1e6}        # Positivity Lagrange Multiplier
  - {dataset: NNPDF_POS_2P24GEV_FLL, maxlambda: 1e6}

############################################################
integrability:
  integdatasets:
  - {dataset: NNPDF_INTEG_3GEV_XT3, maxlambda: 1e2}

############################################################
debug: True
maxcores: 8
