#
# Configuration file for n3fit
#

############################################################
description: Basic runcard

############################################################
# frac: training fraction
# ewk: apply ewk k-factors
# sys: systematics treatment (see systypes)
dataset_inputs:
- { dataset: SLACP_dwsh, frac: 0.5}
- { dataset: NMCPD_dw, frac: 0.5 }
- { dataset: ATLASZPT8TEVMDIST, frac: 0.75, sys: 10, cfac: [QCD] }

############################################################
datacuts:
  t0pdfset     : NNPDF40_nnlo_as_01180 # PDF set to generate t0 covmat
  q2min        : 3.49                # Q2 minimum
  w2min        : 12.5                # W2 minimum
  combocuts    : NNPDF31             # NNPDF3.0 final kin. cuts
  jetptcut_tev : 0                   # jet pt cut for tevatron
  jetptcut_lhc : 0                   # jet pt cut for lhc
  wptcut_lhc   : 30.0                # Minimum pT for W pT diff distributions
  jetycut_tev  : 1e30                # jet rap. cut for tevatron
  jetycut_lhc  : 1e30                # jet rap. cut for lhc
  dymasscut_min: 0                   # dy inv.mass. min cut
  dymasscut_max: 1e30                # dy inv.mass. max cut
  jetcfactcut  : 1e30                # jet cfact. cut

############################################################
theory:
  theoryid: 200       # database id

sampling:
  separate_multiplicative: true
parameters: # This defines the parameter dictionary that is passed to the Model Trainer
  nodes_per_layer: [15, 10, 8]
  activation_per_layer: ['sigmoid', 'sigmoid', 'linear']
  initializer: 'glorot_normal'
  optimizer:
    optimizer_name: 'RMSprop'
    learning_rate: 0.01
    clipnorm: 1.0
  epochs: 900
  positivity:
    multiplier: 1.05 # When any of the multiplier and/or the initial is not set
    initial: # the maxlambda will be used instead to compute these values per dataset
    threshold: 1e-5
  stopping_patience: 0.30 # percentage of the number of epochs
  layer_type: 'dense'
  dropout: 0.0
  threshold_chi2: 5.0

############################################################
trvlseed: 1
nnseed: 2
mcseed: 3
genrep: True     # true = generate MC replicas, false = use real data

fitting:
  # NN23(QED) = sng=0,g=1,v=2,t3=3,ds=4,sp=5,sm=6,(pht=7)
  # EVOL(QED) = sng=0,g=1,v=2,v3=3,v8=4,t3=5,t8=6,(pht=7)
  # EVOLS(QED)= sng=0,g=1,v=2,v8=4,t3=4,t8=5,ds=6,(pht=7)
  # FLVR(QED) = g=0, u=1, ubar=2, d=3, dbar=4, s=5, sbar=6, (pht=7)
  fitbasis: NN31IC # EVOL (7), EVOLQED (8), etc.
  basis:
      # remeber to change the name of PDF accordingly with fitbasis
      - { fl: sng,  smallx: [1.05,1.19], largex: [1.47,2.70], trainable: False }
      - { fl: g,    smallx: [0.94,1.25], largex: [0.11,5.87], trainable: False }
      - { fl: v,    smallx: [0.54,0.75], largex: [1.15,2.76], trainable: False }
      - { fl: v3,   smallx: [0.21,0.57], largex: [1.35,3.08] }
      - { fl: v8,   smallx: [0.52,0.76], largex: [0.77,3.56], trainable: True }
      - { fl: t3,   smallx: [-0.37,1.52], largex: [1.74,3.39] }
      - { fl: t8,   smallx: [0.56,1.29], largex: [1.45,3.03] }
      - { fl: cp,   smallx: [0.12,1.19], largex: [1.83,6.70] }

############################################################
positivity:
  posdatasets:
    - { dataset: POSF2U, maxlambda: 1e6 }  # Positivity Lagrange Multiplier
    - { dataset: POSFLL, maxlambda: 1e4 }

############################################################
integrability:
  integdatasets:
    - {dataset: INTEGXT3,   maxlambda: 1e2}

############################################################
debug: True
maxcores: 8

tensorboard:
  weight_freq: 100
  profiling: False

save: 'weights.h5'
# load: '/path/to/weights.h5/file'
