#
# Configuration file for n3fit
#
################################################################################
description: NNPDF4.0 NNLO baseline fit (nFONLL). Comparable to NNPDF40_nnlo_as_01180_qcd

################################################################################
dataset_inputs:
- {dataset: NMC_NC_NOTFIXED_DW_EM-F2, frac: 0.75, variant: legacy}
- {dataset: NMC_NC_NOTFIXED_P_EM-SIGMARED, frac: 0.75, variant: legacy}
- {dataset: SLAC_NC_NOTFIXED_P_DW_EM-F2, frac: 0.75, variant: legacy}
- {dataset: SLAC_NC_NOTFIXED_D_DW_EM-F2, frac: 0.75, variant: legacy}


################################################################################
datacuts:
  t0pdfset: NNPDF40_nnlo_as_01180
  q2min: 3.49
  w2min: 12.5

################################################################################
# NNLO QCD TRN evolution
theory:
  theoryid: 40_000_000

# For fits <= 4.0 multiplicative and additive uncertainties were sampled separately
sampling:
  separate_multiplicative: False

################################################################################
trvlseed: 591866982
nnseed: 945709987
mcseed: 519562661
genrep: true

################################################################################
parameters: # This defines the parameter dictionary that is passed to the Model Trainer
  nodes_per_layer: [25, 20, 8]
  activation_per_layer: [tanh, tanh, linear]
  initializer: glorot_normal
  optimizer:
    clipnorm: 6.073e-6
    learning_rate: 2.621e-3
    optimizer_name: Nadam
  epochs: 17000
  positivity:
    initial: 184.8
    multiplier:
  integrability:
    initial: 10
    multiplier:
  stopping_patience: 0.1
  layer_type: dense
  dropout: 0.0
  threshold_chi2: 3.5

fitting:
  fitbasis: EVOL
  savepseudodata: True
  basis:
  - {fl: sng, trainable: false, smallx: [1.091, 1.119], largex: [1.471, 3.021]}
  - {fl: g, trainable: false, smallx: [0.7795, 1.095], largex: [2.742, 5.547]}
  - {fl: v, trainable: false, smallx: [0.472, 0.7576], largex: [1.571, 3.559]}
  - {fl: v3, trainable: false, smallx: [0.07483, 0.4501], largex: [1.714, 3.467]}
  - {fl: v8, trainable: false, smallx: [0.5731, 0.779], largex: [1.555, 3.465]}
  - {fl: t3, trainable: false, smallx: [-0.5498, 1.0], largex: [1.778, 3.5]}
  - {fl: t8, trainable: false, smallx: [0.5469, 0.857], largex: [1.555, 3.391]}
  - {fl: t15, trainable: false, smallx: [1.081, 1.142], largex: [1.491, 3.092]}

################################################################################
positivity:
  posdatasets:
  - {dataset: NNPDF_POS_2P24GEV_F2U, maxlambda: 1e6}        # Positivity Lagrange Multiplier
  - {dataset: NNPDF_POS_2P24GEV_F2D, maxlambda: 1e6}
  - {dataset: NNPDF_POS_2P24GEV_F2S, maxlambda: 1e6}
  - {dataset: NNPDF_POS_2P24GEV_FLL-19PTS, maxlambda: 1e6}
  - {dataset: NNPDF_POS_2P24GEV_DYU, maxlambda: 1e10}
  - {dataset: NNPDF_POS_2P24GEV_DYD, maxlambda: 1e10}
  - {dataset: NNPDF_POS_2P24GEV_DYS, maxlambda: 1e10}
  - {dataset: NNPDF_POS_2P24GEV_F2C-17PTS, maxlambda: 1e6}
  - {dataset: NNPDF_POS_2P24GEV_XUQ, maxlambda: 1e6}        # Positivity of MSbar PDFs
  - {dataset: NNPDF_POS_2P24GEV_XUB, maxlambda: 1e6}
  - {dataset: NNPDF_POS_2P24GEV_XDQ, maxlambda: 1e6}
  - {dataset: NNPDF_POS_2P24GEV_XDB, maxlambda: 1e6}
  - {dataset: NNPDF_POS_2P24GEV_XSQ, maxlambda: 1e6}
  - {dataset: NNPDF_POS_2P24GEV_XSB, maxlambda: 1e6}
  - {dataset: NNPDF_POS_2P24GEV_XGL, maxlambda: 1e6}

integrability:
  integdatasets:
  - {dataset: NNPDF_INTEG_3GEV_XT8, maxlambda: 1e2}
  - {dataset: NNPDF_INTEG_3GEV_XT3, maxlambda: 1e2}


added_filter_rules:
    - process_type: POS_XPDF
      rule: "x > 0.1"


################################################################################
debug: false
maxcores: 8
