#
# Configuration file for n3fit
#
############################################################
description: Basic runcard qed

############################################################
# frac: training fraction
# ewk: apply ewk k-factors
# sys: systematics treatment (see systypes)
dataset_inputs:
- {dataset: NMC_NC_NOTFIXED_DW_EM-F2, frac: 0.75, variant: legacy}
- {dataset: SLAC_NC_NOTFIXED_D_DW_EM-F2, frac: 0.75, variant: legacy}
- {dataset: ATLAS_Z0J_8TEV_PT-M, frac: 0.75, cfac: [], variant: legacy_10}


############################################################
datacuts:
  t0pdfset: NNPDF40_nnlo_as_01180  # PDF set to generate t0 covmat
  q2min: 3.49                        # Q2 minimum
  w2min: 12.5                        # W2 minimum

############################################################
theory:
  theoryid: 702     # database id

############################################################
trvlseed: 1551864071
nnseed: 676150632
mcseed: 619859729
save: false
genrep: true      # true = generate MC replicas, false = use real data

parameters: # This defines the parameter dictionary that is passed to the Model Trainer
  nodes_per_layer: [25, 20, 8]
  activation_per_layer: [tanh, tanh, linear]
  initializer: glorot_normal
  optimizer:
    clipnorm: 6.073e-6
    learning_rate: 2.621e-3
    optimizer_name: Nadam
  epochs: 900
  positivity:
    initial: 184.8
    multiplier:
  integrability:
    initial: 10
    multiplier:
  stopping_patience: 0.1
  layer_type: dense
  dropout: 0.0
  threshold_chi2: 3.5

fitting:
  fitbasis: EVOL  # EVOL (7), EVOLQED (8), etc.
  basis:
  - {fl: sng, trainable: false, smallx: [1.089, 1.117], largex: [1.462, 3.008]}
  - {fl: g, trainable: false, smallx: [0.7542, 1.105], largex: [2.826, 5.407]}
  - {fl: v, trainable: false, smallx: [0.4715, 0.7253], largex: [1.564, 3.48]}
  - {fl: v3, trainable: false, smallx: [0.1372, 0.4205], largex: [1.755, 3.451]}
  - {fl: v8, trainable: false, smallx: [0.5641, 0.7702], largex: [1.513, 3.433]}
  - {fl: t3, trainable: false, smallx: [-0.4942, 0.9992], largex: [1.751, 3.383]}
  - {fl: t8, trainable: false, smallx: [0.532, 0.8572], largex: [1.541, 3.349]}
  - {fl: t15, trainable: false, smallx: [1.052, 1.14], largex: [1.487, 3.09]}

############################################################
positivity:
  posdatasets:
  - {dataset: NNPDF_POS_2P24GEV_F2U, maxlambda: 1e6}        # Positivity Lagrange Multiplier
  - {dataset: NNPDF_POS_2P24GEV_FLL-19PTS, maxlambda: 1e6}

############################################################
integrability:
  integdatasets:
  - {dataset: NNPDF_INTEG_3GEV_XT3, maxlambda: 1e2}

############################################################
debug: True
maxcores: 8

fiatlux:
  luxset: NNPDF40_nnlo_as_01180
  additional_errors: true # should be set to true only for the last iteration
  luxseed: 1234567890
  eps_base: 1e-2
