#
# Configuration file for n3fit
#
############################################################
description: Regression runcard for the automatic github fitbot

############################################################
dataset_inputs:
- {dataset: NMC_NC_NOTFIXED_EM-F2, frac: 0.75, variant: legacy_dw}
- {dataset: NMC_NC_NOTFIXED_P_EM-SIGMARED, frac: 0.75, variant: legacy}
- {dataset: SLAC_NC_NOTFIXED_P_EM-F2, frac: 0.75, variant: legacy_dw}
- {dataset: SLAC_NC_NOTFIXED_D_EM-F2, frac: 0.75, variant: legacy_dw}
- {dataset: CHORUS_CC_NOTFIXED_PB_NB-SIGMARED, frac: 0.75, variant: legacy_dw}
- {dataset: NUTEV_CC_NOTFIXED_FE_NU-SIGMARED, cfac: [MAS], frac: 0.75, variant: legacy_dw}
- {dataset: HERA_NC_225GEV_EP-SIGMARED, frac: 0.75}
- {dataset: HERA_NC_251GEV_EP-SIGMARED, frac: 0.75}
- {dataset: HERA_NC_300GEV_EP-SIGMARED, frac: 0.75}
- {dataset: HERA_NC_318GEV_EP-SIGMARED, frac: 0.75}
- {dataset: HERA_CC_318GEV_EM-SIGMARED, frac: 0.75}
- {dataset: DYE605_Z0_38P8GEV_DW_PXSEC, frac: 0.75}
- {dataset: ATLAS_Z0_7TEV_36PB_ETA, frac: 0.75}
- {dataset: ATLAS_Z0_7TEV_49FB_HIMASS, frac: 0.75}
- {dataset: ATLAS_WPWM_13TEV_TOT, frac: 0.75, cfac: [NRM]}
- {dataset: ATLAS_WJ_8TEV_WP-PT, frac: 0.75}
- {dataset: ATLAS_Z0J_8TEV_PT-Y, frac: 0.75}
- {dataset: ATLAS_TTBAR_7TEV_TOT_X-SEC, frac: 0.75}
- {dataset: ATLAS_TTBAR_8TEV_TOT_X-SEC, frac: 0.75}
- {dataset: ATLAS_1JET_8TEV_R06_PTY, frac: 0.75, variant: legacy_data}
- {dataset: CMS_WPWM_7TEV_MUON_ASY, frac: 0.75}
- {dataset: CMS_Z0_7TEV_DIMUON_2D, frac: 0.75}
- {dataset: CMS_WPWM_8TEV_MUON_Y, frac: 0.75}
- {dataset: CMS_SINGLETOP_8TEV_TCHANNEL-XSEC, frac: 0.75}
- {dataset: CMS_SINGLETOP_13TEV_TCHANNEL-XSEC, frac: 0.75}
- {dataset: LHCB_Z0_7TEV_DIELECTRON_Y, frac: 0.75}
- {dataset: LHCB_WPWM_7TEV_MUON_Y, frac: 0.75, cfac: [NRM]}
- {dataset: LHCB_Z0_13TEV_DIELECTRON-Y, frac: 0.75}

############################################################
datacuts:
  t0pdfset: 251023-jcm-nnpdf41-001 # PDF set to generate t0 covmat
  q2min   : 3.49                # Q2 minimum
  w2min   : 12.5                # W2 minimum

############################################################
theory:
  theoryid: 41000000

############################################################
trvlseed: 1
nnseed: 2
mcseed: 3
load: 'developing.weights.h5'
genrep: true   # true = generate MC replicas, false = use real data

parameters: # This defines the parameter dictionary that is passed to the Model Trainer
  nodes_per_layer: [50, 35, 25, 8]
  activation_per_layer: ['tanh', 'sigmoid', 'sigmoid', 'linear']
  initializer: 'glorot_normal'
  optimizer:
    clipnorm: 1.e-5
    learning_rate: 3.e-3
    optimizer_name: Nadam
  epochs: 5000
  integrability:
    initial:
    multiplier: 1.03
  positivity:
      initial:
      multiplier: 1.10
  stopping_patience: 0.1 # percentage of the number of epochs
  layer_type: 'dense'
  dropout: 0.001
  interpolation_points: 7

fitting:
  fitbasis: EVOL
  savepseudodata: False
  basis:
  - {fl: sng , trainable: false , smallx: [1.093   , 1.121]  , largex: [0., 0.]}
  - {fl: g   , trainable: false , smallx: [0.8329  , 1.071]  , largex: [0., 0.]}
  - {fl: v   , trainable: false , smallx: [0.5202  , 0.7431] , largex: [0., 0.]}
  - {fl: v3  , trainable: false , smallx: [0.1205  , 0.4839] , largex: [0., 0.]}
  - {fl: v8  , trainable: false , smallx: [0.5864  , 0.7987] , largex: [0., 0.]}
  - {fl: t3  , trainable: false , smallx: [-0.5019 , 1.126]  , largex: [0., 0.]}
  - {fl: t8  , trainable: false , smallx: [0.6305  , 0.8806] , largex: [0., 0.]}
  - {fl: t15 , trainable: false , smallx: [1.087   , 1.139]  , largex: [0., 0.]}

############################################################
positivity:
  posdatasets:
  - {dataset: NNPDF_POS_2P24GEV_F2U, maxlambda: 1e6}        # Positivity Lagrange Multiplier
  - {dataset: NNPDF_POS_2P24GEV_F2D, maxlambda: 1e6}
  - {dataset: NNPDF_POS_2P24GEV_DYU, maxlambda: 1e10}
  - {dataset: NNPDF_POS_2P24GEV_DYD, maxlambda: 1e10}
  - {dataset: NNPDF_POS_2P24GEV_DYS, maxlambda: 1e10}
  - {dataset: NNPDF_POS_2P24GEV_XDB, maxlambda: 1e6}
  - {dataset: NNPDF_POS_2P24GEV_XSQ, maxlambda: 1e6}
  - {dataset: NNPDF_POS_2P24GEV_XSB, maxlambda: 1e6}
  - {dataset: NNPDF_POS_2P24GEV_XGL, maxlambda: 1e6}

integrability:
  integdatasets:
  - {dataset: NNPDF_INTEG_3GEV_XT8, maxlambda: 1e2}
  - {dataset: NNPDF_INTEG_3GEV_XT3, maxlambda: 1e2}

############################################################
debug: True
maxcores: 4
