## Load image with software requirements for libnnpdf
image: zaharid/conda-centos

stages:
    - build-deploy


#Set to "true" to generate builds for non-default branches
variables:
    UPLOAD_NON_MASTER: "false"

## Run the configure and make tests
job1:
    variables:
        CONDA_PY: "36"
    stage: build-deploy
    script: ".ciscripts/build-deploy.sh"

job2:
    variables:
        CONDA_PY: "37"
    stage: build-deploy
    script: ".ciscripts/build-deploy.sh"

