#!/usr/bin/env python
# -*- coding: utf-8 -*-
""" Fit Manager"""

__authors__ = 'Stefano Carrazza, et at.'
__license__ = 'GPL'
__version__ = '1.0.0'
__email__ = 'stefano.carrazza@mi.infn.it'

import os
import sys
import argparse
import shutil
from subprocess import PIPE, Popen
sys.path.append('../tools/')

modes = ['download','upload']
webpath = "nnpdf@pcteserver.mi.infn.it:/home/nnpdf/WEB/fits/"

def download(set):
    """
    Downloads the selected set of PDFs
    """
    try:
        tar = set + ".tgz"
        os.system("scp %s%s ." % (webpath,tar))
        os.system("tar -xzf " + tar)
        os.system("rm %s" % tar)
    except:
        print ("Error downloading PDF set")
        raise

    try:
        # Copy grid to LHAPATH
        lhapath = Popen(["lhapdf-config","--datadir"],stdout=PIPE).communicate()[0]
        lhapath = lhapath.decode()
        lhapath = lhapath.replace("\n","/")
        src     = set + "/nnfit/" + set
        dst = lhapath + set
        shutil.copytree(src,dst)
    except:
        print ("Error copying PDF set to LHAPDF path")
        raise

def upload(set):
    """
    Uploads the desired set of PDFs
    """
    tartemp = 'tar -zcf {0}.tgz --exclude={0}.dat {0}/'
    tarcommand = tartemp.format(set)

    try:
        os.system(tarcommand)
        os.system("scp " + set + ".tgz " + webpath)
        os.system("rm %s" % set + ".tgz")
    except:
        raise

def main(mode,fit):

    # no TUI, download or upload directly
    if fit != None:
        if mode == modes[0]: download(fit[0])
        if mode == modes[1]: upload(fit[0])

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument('mode',choices=modes, help='download or upload pdf set')
    parser.add_argument('-f','--fit',nargs=1, help='fit folder', default=None)
    args = parser.parse_args()
    mainargs = vars(args)
    main(**mainargs)
