#!/bin/bash
# Increments the FK table in the argument by the value in the second argument
if [ -z "$1"] ; then
    echo "No first argument supplied"
    exit 1
fi

if [ -z "$2"] ; then
    echo "No second argument supplied"
    exit 1
fi

# Fetch information on header size and number of datapoints
NHEADER=$( (grep -n -m1 '{FastKernel' $1 | cut -f1 -d:) )
ARRIN=($(grep 'NDATA:' $1)); NDAT=$(( ${ARRIN[1]} + $2 ))

# Correct for total number of datapoints
cat $1 | awk -v ndat="$NDAT" -v nhead="$NHEADER" ' NR <= nhead {if ($1=="*NDATA:") print $1, ndat; else print;}'
# Correct for data indices
cat $1 | awk -v ninc="$2" -v nhead="$NHEADER" 'NR > nhead {$1=$1+ninc;print;}'

exit 0;
