#!/bin/bash

IDX=0
NDAT=0
TDAT=0

for var in "$@"
do

    # Check file exists
    if [ ! -f $var ];
    then
        echo "File $var does not exist."
	    exit 1;
    fi

    #Get Nx/NData
    ARRIN=($(grep 'NX:' $var))
    NX=${ARRIN[1]}

    ARRIN=($(grep 'NDATA:' $var))
    NDAT=${ARRIN[1]}
    TDAT=$(($TDAT + $NDAT))

    NHEADER=$( (grep -n -m1 '{FastKernel' $var | cut -f1 -d:) )

    cDat[$IDX]=$TDAT                #Array for number of datapoints
    cX[$IDX]=$NX                    #Array for number of X points
    cHead[$IDX]=$NHEADER            #Array for number of header lines
    IDX=$(( $IDX+1 ))

done

for ix in $cX
do
	if [ $ix != ${cX[0]} ] 
	then
		echo "Error: Number of X points in grids is not equal, "$ix" vs "${cX[0]}
		exit 2;
	fi
done	

IDX=0
for var in "$@"
do
    if [ $IDX -eq 0 ]
    then
	cat $var | awk -v ndat="${TDAT}" '{if ($1=="*NDATA:") print $1, ndat; else print;}'
    else
	cat $var | awk -v dat="${cDat[$(( $IDX-1 ))]}" -v nhead="${cHead[$IDX]}" 'NR > nhead {$1=$1+dat;print;}'
    fi
    IDX=$(( $IDX+1 ))
done

exit 0;
