#! /usr/bin/env bash

# These variables need to exist
prefix=/opt/libnnpdf
exec_prefix=/opt/libnnpdf

if [[ $# -eq 0 || -n $( echo $* | egrep -- "--help|-h" ) ]]; then
    echo
    echo "nnpdf-config: configuration tool for libnnpdf"
    echo
    echo "Usage: nnpdf-config [[--help|-h] | [--prefix] | [--ldflags]]"
    echo "Options:"
    echo "  --help | -h    : show this help message"
    echo "  --prefix       : show the installation prefix (cf. autoconf)"
    echo "  --incdir       : show the path to the nnpdf header directory (for C++ interface)"
    echo "  --libdir       : show the path to the nnpdf library directory"
    echo "  --cppflags     : get compiler flags for use with the C preprocessor stage of C++ compilation"
    echo "  --ldflags      : get compiler flags for use with the linker stage of any compilation"
    echo "  --safemode     : get a boolean with the safemode option"
    echo "  --version      : returns libnnpdf release version number"
fi

OUT=""

tmp=$( echo "$*" | egrep -- '--\<prefix\>')
test -n "$tmp" && OUT="$OUT /opt/libnnpdf"

tmp=$( echo "$*" | egrep -- '--\<incdir\>')
test -n "$tmp" && OUT="$OUT "

tmp=$( echo "$*" | egrep -- '--\<cppflags\>')
test -n "$tmp" && OUT="$OUT -I -std=c++11"

tmp=$( echo "$*" | egrep -- '--\<libdir\>')
test -n "$tmp" && OUT="$OUT "

tmp=$( echo "$*" | egrep -- '--\<ldflags\>')
test -n "$tmp" && OUT="$OUT -L -lnnpdf -lgsl"

tmp=$( echo "$*" | egrep -- '--\<safemode\>')

a="1"
if [ -n "#define SSE_CONV" ]; then
    a="0"
fi
test -n "$tmp" && OUT="$OUT $a"

## Version
tmp=$( echo "$*" | egrep -- '--\<version\>')
test -n "$tmp" && OUT="$OUT "

echo $OUT
