name: Doctests

on: [push, pull_request]

concurrency:
  group: doctests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  doctests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/install_conda_pip
        with:
          python-version: "3.13"

      - name: Run n3fit doctests
        shell: bash -l {0}
        working-directory: n3fit/src/n3fit
        run: pytest --doctest-modules -W ignore --ignore=tests --ignore=hyper_optimization .

      - name: Run validphys doctests
        shell: bash -l {0}
        working-directory: validphys2/src/validphys
        run: pytest --doctest-modules -W ignore --ignore=tests .