name: Redo regressions

# Last update: 17/03/2026

# start job only for PRs when a label is added
on: [push]
  # pull_request:
  #   types: [labeled]

# some general variables
env:
  # https://keras.io/getting_started/faq/#how-can-i-obtain-reproducible-results-using-keras-during-development
  PYTHONHASHSEED: "0"

jobs:
  build:
    # if: contains(github.event.pull_request.labels.*.name, 'redo-regressions')
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/nnpdf/nnpdf-container:latest
    env:
      NETRC_FILE: ${{ secrets.NETRC_FILE }}
      NNPDF_SSH_KEY: ${{ secrets.NNPDF_SSH_KEY }}
    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.ref }}
    - name: Install NNPDF
      run: |
        git config --global --add safe.directory "${GITHUB_WORKSPACE}"
        echo "$NETRC_FILE" | base64 --decode > ~/.netrc
        pip install -e .[qed,tests,hyperopt]
    - name: Regenerate regressions
      run: |
        pytest extra_tests/regression_checks.py --regenerate True
    - name: Commit
      run: |
        git config user.name "Redo regressions bot"
        git config user.email "<>"
        git add extra_tests/regression_fits/*
        git status
        git commit -m "Automatically regenerated regressions from PR ${{ github.event.number }}, branch ${{ github.event.pull_request.head.ref }}."
        git push origin "${{ github.event.pull_request.head.ref }}"
