name: Collection of regression tests

on: [push]

env:
  # https://keras.io/getting_started/faq/#how-can-i-obtain-reproducible-results-using-keras-during-development
  # However, results might change between different versions of keras.
  PYTHONHASHSEED: "0"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NETRC_FILE: ${{ secrets.NETRC_FILE }}
      NNPDF_SSH_KEY: ${{ secrets.NNPDF_SSH_KEY }}
    steps:
    - uses: actions/checkout@v4
    - uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: "3.12"
        use-mamba: true
        auto-update-conda: true
        activate-environment: test
    - name: Setup conda and install LHAPDF and pandoc
      shell: bash -l {0}
      run: |
        echo "$NETRC_FILE" | base64 --decode > ~/.netrc
        conda config --remove channels defaults
        conda config --append channels conda-forge
        conda config --prepend channels https://packages.nnpdf.science/public
        conda config --set show_channel_urls true
        conda install lhapdf pandoc
    - name: Install nnpdf with testing and qed extras
      shell: bash -l {0}
      run: |
        pip install .[qed,tests]
    - name: Test n3fit and validphys
      shell: bash -l {0}
      run: |
        pytest extra_tests/regression_checks.py
