# A single CI script with github workflow.
name: Automatic Fit

# start job only for PRs when a label is added.
on:
  pull_request:
    types: [labeled]

# some general variables
env:
  N3FIT_MAXNREP: 20 # total number of replicas to fit
  POSTFIT_NREP: 16 # requested replicas for postfit
  REFERENCE_SET: NNBOT-d3034a7cc-2021-06-11 # reference set for vp
  CONDA_PY: 37

jobs:
  build:
    # perform build only if PR has run-fit-bot label
    if: contains(github.event.pull_request.labels.*.name, 'run-fit-bot')
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8]
    runs-on: ${{ matrix.os }}
    env:
      NETRC_FILE: ${{ secrets.NETRC_FILE }}
    steps:
    - uses: actions/checkout@v1
    - uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.NNPDF_SSA }}
        name: id_rsa
        known_hosts: ${{ secrets.NNPDF_HOSTS_KEY }}
        config: |
          Host nnpdf
          Hostname nnpdf.fisica.unimi.it
    - name: Setup conda and install conda-build
      shell: bash -l {0}
      run: |
        echo "$NETRC_FILE" | base64 --decode > ~/.netrc
        echo "Running"
        echo "I'm github" > test.txt
        scp test.txt nnpdf@nnpdf:test.txt
